### ISSUE TITLE
好歹也搞几个gif来看看效果撒

### ISSUE THREAD

**Issue by rcj60560** [yangkun19921001/CustomViewSample#1]
@yangkun19921001

**Comment by yangkun19921001** [comment]
@rcj60560 可以参考我写的[高级 UI 系列博客](https://juejin.im/post/5e25d317e51d4558864b1877)。里面有详细的介绍
![image](https://user-images.githubusercontent.com/20500834/74802306-6fe5bd80-5314-11ea-868a-b0947af82e8c.png)
